---
apiVersion: triggers.tekton.dev/v1alpha1 
kind: TriggerTemplate 
metadata: 
  name: image-pipeline-trigger-template
spec: 
  params: 
    - name: gitrevision 
      description: The git revision sha
    - name: image 
      description: The image to build and push
    - name: change_path
      description: The path that changed
  resourcetemplates: 
    - apiVersion: tekton.dev/v1beta1 
      kind: PipelineRun 
      metadata: 
        name: $(tt.params.image)-container-build-$(tt.params.gitrevision)
        namespace: pipelines
      spec:
        serviceAccountName: tekton-sa
        pipelineRef: 
          name: example-image-build-pipeline
        params: 
          - name: IMAGE_NAME
            value: $(tt.params.image)
          - name: REGISTRY_HOSTNAME
            value: "docker.io" 
          - name: REGISTRY_NAMESPACE
            value: "cengleby86" 
          - name: IMAGE_TAG
            value: $(tt.params.gitrevision)
          - name: GITHUB_REPO
            value: 'https://github.com/poc-examples/container-workloads.git'
          - name: GITHUB_BRANCH
            value: 'main'
        podTemplate:
          securityContext:
            runAsUser: 1001
            fsGroup: 65532
        workspaces:
        - name: source
          persistentVolumeClaim:
            claimName: clone-output
        - name: containers
          persistentVolumeClaim:
            claimName: varlibcontainers
        - name: credentials
          secret:
            secretName: quay-secret
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-binding
spec:
  params:
    - name: gitrevision
      value: "$(body.after)"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-event-listener
spec:
  serviceAccountName: tekton-sa
  triggers:
    - name: github-listener
      interceptors:
        - ref:
            name: "github"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
          # - name: "secretRef"
          #   value:
          #     secretName: github-secret
          #     secretKey: secretToken 
          - name: "eventTypes"
            value: ["push"]
          - name: "addChangedFiles"
            value:
              enabled: true
        - ref:
            name: cel
          params:
          - name: filter
            value: extensions.changed_files.matches('chatbot-services/chat-window/')
      bindings:
        - ref: github-binding
          kind: TriggerBinding
        - name: change_path
          value: "chatbot-services/chat-window/"
        - name: image
          value: "chat-window"
      template:
        ref: image-pipeline-trigger-template
