---
apiVersion: triggers.tekton.dev/v1alpha1 
kind: TriggerTemplate 
metadata: 
  name: image-pipeline-trigger-template
spec: 
  params: 
    - name: gitrevision 
      description: The git revision sha
    - name: image 
      description: The image to build and push
    - name: change_path
      description: The path that changed
  resourcetemplates: 
    - apiVersion: tekton.dev/v1beta1 
      kind: PipelineRun 
      metadata: 
        name: $(tt.params.image)-container-build-$(tt.params.gitrevision)
        namespace: pipelines
      spec:
        serviceAccountName: tekton-sa
        pipelineRef: 
          name: example-image-build-pipeline
        params: 
          - name: IMAGE_NAME
            value: $(tt.params.image)
          - name: CHANGE_PATH
            value: $(tt.params.change_path)
          - name: REGISTRY_HOSTNAME
            value: "default-route-openshift-image-registry.apps.xr42gryb.eastus.aroapp.io" 
          - name: REGISTRY_NAMESPACE
            value: "pipelines" 
          - name: IMAGE_TAG
            value: $(tt.params.gitrevision)
          - name: GITHUB_REPO
            value: 'https://gitlab.apps.xr42gryb.eastus.aroapp.io/root/container-library.git'
          - name: GITHUB_BRANCH
            value: 'main'
        podTemplate:
          securityContext:
            runAsUser: 1001
            fsGroup: 65532
        workspaces:
        - name: source
          persistentVolumeClaim:
            claimName: clone-output
        - name: containers
          persistentVolumeClaim:
            claimName: varlibcontainers
        - name: credentials
          secret:
            secretName: tekton-sa-dockercfg-wttg2
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-binding
spec:
  params:
    - name: gitrevision
      value: "$(body.after)"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-event-listener
spec:
  serviceAccountName: tekton-sa
  triggers:
    - name: chat-window
      interceptors:
        - ref:
            name: "gitlab"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
          - name: "eventTypes"
            value: ["Push Hook"]
          # - name: "addChangedFiles"
          #   value:
          #     enabled: true
        - ref:
            name: cel
          params:
          - name: filter
            value: body.commits[0].modified.exists_one(x, x.startsWith('chatbot-services/chat-window'))
          - name: "overlays"
            value:
            - key: truncated_sha
              expression: "body.after.truncate(7)"
      bindings:
        - name: gitrevision
          value: $(extensions.truncated_sha)
        - name: change_path
          value: "chatbot-services/chat-window/"
        - name: image
          value: "chat-window"
      template:
        ref: image-pipeline-trigger-template
